// Generated by CoffeeScript 1.3.3

/*
## Fancy Settings by Frank Kohlhepp
## Copyright (c) 2011 - 2012 Frank Kohlhepp
## https://github.com/frankkohlhepp/fancy-settings
## License: LGPL v2.1
*/


(function() {
  var lang, _ref;

  lang = navigator.language.split("-")[0];

  if ((_ref = window.i18n) == null) {
    window.i18n = {};
  }

  window.i18n.get = function(value, myLang) {
    if (myLang == null) {
      myLang = lang;
    }
    if (value === "lang") {
      return myLang;
    }
    if (this[value] != null) {
      value = this[value];
      if (value[myLang] != null) {
        return value[myLang];
      } else if (value.en != null) {
        return value.en;
      } else {
        return Object.values(value)[0];
      }
    } else {
      return value;
    }
  };

}).call(this);
